# Generated by Django 5.2.1 on 2025-05-30 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_umkm', models.CharField(blank=True, max_length=100, null=True)),
                ('deskripsi_umkm', models.TextField(blank=True, null=True)),
                ('nohp_umkm', models.CharField(blank=True, max_length=20, null=True)),
                ('logo_umkm', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_lowongan', models.TextField(blank=True, null=True)),
                ('alamat_lowongan', models.CharField(blank=True, max_length=200, null=True)),
                ('status_lowongan', models.CharField(blank=True, choices=[('1', 'Mencari'), ('2', 'Tutup')], null=True)),
                ('umkm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.umkm')),
            ],
        ),
    ]
