# Generated by Django 5.2.1 on 2025-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkm',
            name='has_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='umkm',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
