# Generated by Django 5.2.1 on 2025-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_umkm_proposal_umkm'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkm',
            name='nama_penanggung_jawab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
