# Generated by Django 5.2.1 on 2025-05-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_umkm_nama_penanggung_jawab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='umkm',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Diterima'), ('2', 'Ditolak')], null=True),
        ),
    ]
