# Generated by Django 5.2.1 on 2025-05-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_lowongan_judul_lowongan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowongan',
            name='status_lowongan',
            field=models.CharField(blank=True, choices=[('1', 'Mencari'), ('2', 'Tutup')], default='1', null=True),
        ),
    ]
