# Generated by Django 5.2.1 on 2025-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_kategori_detailkategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowongan',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
