# Generated by Django 5.2.1 on 2025-05-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_lowongan_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowongan',
            name='lamaran_dibuka',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='lamaran_ditutup',
            field=models.DateField(blank=True, null=True),
        ),
    ]
