# Generated by Django 5.2.1 on 2025-05-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_lowongan_lamaran_dibuka_lowongan_lamaran_ditutup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailkategori',
            name='lowongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='backend.lowongan'),
        ),
    ]
