# Generated by Django 5.2.1 on 2025-05-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_mahasiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Nganggur'), ('2', 'Mengajukan'), ('3', 'Sedang Magang')], default='1', max_length=20, null=True),
        ),
    ]
