# Generated by Django 5.2.1 on 2025-05-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_mahasiswa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.kategori'),
        ),
    ]
