# Generated by Django 5.2.1 on 2025-05-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_mahasiswa_jurusan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='surat_pengajuan',
            field=models.FileField(blank=True, null=True, upload_to='pengajuan/'),
        ),
    ]
