# Generated by Django 5.2.1 on 2025-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_mahasiswa_cv_mahasiswa_surat_pengajuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
