# Generated by Django 5.2.1 on 2025-05-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_mahasiswa_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowongan',
            name='mulai_magang',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='selesai_magang',
            field=models.DateField(blank=True, null=True),
        ),
    ]
